#!/usr/bin/env bash

hc () {
    herbstclient "$@"
}

hc emit_hook reload
xsetroot -solid '#00000'

# ░█░█░█▀▀░█░█░█▀▀░░░█▀▄░▀█▀░█▀█░█▀▄░▀█▀░█▀█░█▀▀
# ░█▀▄░█▀▀░░█░░▀▀█░░░█▀▄░░█░░█░█░█░█░░█░░█░█░█░█
# ░▀░▀░▀▀▀░░▀░░▀▀▀░░░▀▀░░▀▀▀░▀░▀░▀▀░░▀▀▀░▀░▀░▀▀▀
Mod=Mod4
hc keyunbind --all


# focusing clients
hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# moving clients in tiling and floating mode
hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right

# splitting frames
hc keybind $Mod-u split bottom 0.5
hc keybind $Mod-o split right 0.5
# hc keybind $Mod-e split explode
hc keybind $Mod-r remove
resizestep=0.02
hc keybind $Mod-Control-h resize left +$resizestep
hc keybind $Mod-Control-j resize down +$resizestep
hc keybind $Mod-Control-k resize up +$resizestep
hc keybind $Mod-Control-l resize right +$resizestep
hc keybind $Mod-Control-Left resize left +$resizestep
hc keybind $Mod-Control-Down resize down +$resizestep
hc keybind $Mod-Control-Up resize up +$resizestep
hc keybind $Mod-Control-Right resize right +$resizestep

# Peak Left Peak Right
hc keybind $Mod-Tab use_index -1 --skip-visible
hc keybind $Mod-e use_index +1 --skip-visible

# cyle through monitors
hc keybind $Mod-BackSpace   cycle_monitor

# mouse
hc mouseunbind --all
hc mousebind Button2 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# Close App
hc keybind $Mod-q close

# Reload Config
hc keybind $Mod-Shift-r reload

# App Keybind
TERMINAL="kitty"
hc keybind $Mod-Return spawn "${TERMINAL:-xterm}"
hc keybind $Mod-d spawn rofi -show drun

# Brightness Keybind
hc keybind XF86MonBrightnessUp spawn brightnessctl s 5%+
hc keybind XF86MonBrightnessDown spawn brightnessctl s 5%-

# Rofi Menu to change layout
hc keybind $Mod-Shift-space spawn ~/.config/herbstluftwm/herbscript/set_layouts.sh

# Cycle through layouts
hc keybind $Mod-space cycle_layout +1

# Cycle through clients within current frame
hc keybind $Mod-c cycle +1

# Fullscreen Toggle
hc keybind $Mod-f fullscreen toggle

hc keybind $Mod-Ctrl-s mktemp string T1 T2 chain \
    , substitute M1 monitors.focus.index substitute T monitors.focus.my_tag get_attr monitors.[M1].my_tag T1 \
    , focus_monitor 1 \
    , substitute M2 monitors.focus.index substitute T monitors.focus.my_tag get_attr monitors.[M2].my_tag T2 \
    , use_attr T1 \
    , focus_monitor 0 \
    , use_attr T2


# ░▀█▀░█░█░█▀▀░█▄█░█▀▀░█▀▀
# ░░█░░█▀█░█▀▀░█░█░█▀▀░▀▀█
# ░░▀░░▀░▀░▀▀▀░▀░▀░▀▀▀░▀▀▀
hc set frame_bg_transparent on
hc set window_gap 5


# ░▀█▀░█▀█░█▀▀░█▀▀
# ░░█░░█▀█░█░█░▀▀█
# ░░▀░░▀░▀░▀▀▀░▀▀▀
tag_names=( {1..6} )
tag_keys=( {1..6} 0 )
hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}" ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if [ -n "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done
extra_tags=( discord scratchpad )
for i in "$extra_tags" ; do
    hc add "$i"
done

# Monitor
hc detect_monitors

# ░█░░░█▀█░█░█░█▀█░█░█░▀█▀░█▀▀
# ░█░░░█▀█░░█░░█░█░█░█░░█░░▀▀█
# ░▀▀▀░▀░▀░░▀░░▀▀▀░▀▀▀░░▀░░▀▀▀
for tag in "${tag_names[@]}" "${extra_tags[@]}" ; do
    hc set_attr tags.by-name.$tag.tiling.root.algorithm horizontal
done


# ░█▀▄░█░█░█░░░█▀▀░█▀▀
# ░█▀▄░█░█░█░░░█▀▀░▀▀█
# ░▀░▀░▀▀▀░▀▀▀░▀▀▀░▀▀▀
hc unrule -F
hc rule focus=on
hc set tree_style '╾│ ├└╼─┐'
hc set swap_monitors_to_get_tag 0
# rules for discord
hc rule class="discord" tag="discord"
hc keybind $Mod-Shift-d spawn ~/.config/herbstluftwm/herbscript/official/scratchpad.sh discord

# rules for terminal scratchpad
hc keybind $Mod-Shift-Return spawn ~/.config/herbstluftwm/herbscript/official/scratchpad.sh scratchpad
hc unlock

# ░█▀█░█░█░▀█▀░█▀█░█▀▀░▀█▀░█▀█░█▀▄░▀█▀░█▀▀
# ░█▀█░█░█░░█░░█░█░▀▀█░░█░░█▀█░█▀▄░░█░░▀▀█
# ░▀░▀░▀▀▀░░▀░░▀▀▀░▀▀▀░░▀░░▀░▀░▀░▀░░▀░░▀▀▀

setxkbmap -option grp:switch,grp:alt_shift_toggle,grp_led:­scroll us,th

spawn_polybar() {
    if type "xrandr"; then
        for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
            MONITOR=$m polybar --reload main &
        done
    else
        polybar --reload main &
    fi
}
pgrep "polybar" > "/dev/null" || spawn_polybar

pgrep "picom" > "/dev/null" || hc spawn picom -b
nitrogen --restore
wal -R
pgrep "nm-applet" > "/dev/null" || hc spawn nm-applet
pgrep "Discord" > "/dev/null" || hc spawn discord
